import ReactDOM from 'react-dom/client'
// import App from './01_类组件和函数式组件/App_class'
// import App from './02_类组件的生命周期函数/App'
// import App from './03_组件嵌套开发/App'
// import App from './04_组件之间通信/App'
// import App from './05_组件之间的通信-子传父/App'
// import App from './06_组件通信案例练习/App'
// import App from './07_组件内插槽的实现/App'
// import App from './08_组件间的作用域插槽/App'
// import App from './09_context上下文数据共享使用/App'
// import App from './10_非父子组件传值（事件总线）/App'
// import App from './11_setState的多种用法/App'
// import App from './12_react组件性能优化/App'
// import App from './13_purecomponent使用/App'
// import App from './14_三种Ref获取元素DOM方法/App'
// import App from './14_获取DOM与获取组件实例/App'
// import App from './15_受控和非受控组件/App'
// import App from './16_React中的高阶组件/01_高阶组件的定义与使用'
// import App from './16_React中的高阶组件/02_高阶组件应用一：注入props'
// import App from './16_React中的高阶组件/03_高阶组件与context对象相结合'
import App from './16_React中的高阶组件/04_登录鉴权'

const root = ReactDOM.createRoot(document.getElementById('root'))
root.render(<App name="LYJC" />)
